/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesPolicyBriefsRouteImport } from './routes/resources.policy-briefs'
import { Route as ResourcesGalleryRouteImport } from './routes/resources.gallery'
import { Route as ResourcesBlogsRouteImport } from './routes/resources.blogs'
import { Route as ReportsProjectReportsRouteImport } from './routes/reports.project-reports'
import { Route as ReportsFinancialReportsRouteImport } from './routes/reports.financial-reports'
import { Route as ReportsAnnualReportsRouteImport } from './routes/reports.annual-reports'
import { Route as ProgramsUpcomingProgramsRouteImport } from './routes/programs.upcoming-programs'
import { Route as ProgramsSpecialProgramsRouteImport } from './routes/programs.special-programs'
import { Route as ProgramsOurKeyProgramsRouteImport } from './routes/programs.our-key-programs'
import { Route as ProgramsCommunityDialogueProgramsRouteImport } from './routes/programs.community-dialogue-programs'
import { Route as ResourcesBlogsSlugRouteImport } from './routes/resources.blogs.$slug'
import { Route as ProgramsUpcomingProgramsSlugRouteImport } from './routes/programs.upcoming-programs.$slug'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPolicyBriefsRoute = ResourcesPolicyBriefsRouteImport.update({
  id: '/policy-briefs',
  path: '/policy-briefs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesGalleryRoute = ResourcesGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesBlogsRoute = ResourcesBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ReportsProjectReportsRoute = ReportsProjectReportsRouteImport.update({
  id: '/project-reports',
  path: '/project-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsFinancialReportsRoute = ReportsFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAnnualReportsRoute = ReportsAnnualReportsRouteImport.update({
  id: '/annual-reports',
  path: '/annual-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ProgramsUpcomingProgramsRoute =
  ProgramsUpcomingProgramsRouteImport.update({
    id: '/upcoming-programs',
    path: '/upcoming-programs',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsSpecialProgramsRoute = ProgramsSpecialProgramsRouteImport.update({
  id: '/special-programs',
  path: '/special-programs',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsOurKeyProgramsRoute = ProgramsOurKeyProgramsRouteImport.update({
  id: '/our-key-programs',
  path: '/our-key-programs',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsCommunityDialogueProgramsRoute =
  ProgramsCommunityDialogueProgramsRouteImport.update({
    id: '/community-dialogue-programs',
    path: '/community-dialogue-programs',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ResourcesBlogsSlugRoute = ResourcesBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesBlogsRoute,
} as any)
const ProgramsUpcomingProgramsSlugRoute =
  ProgramsUpcomingProgramsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ProgramsUpcomingProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LeadershipRoute: typeof LeadershipRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/policy-briefs': {
      id: '/resources/policy-briefs'
      path: '/policy-briefs'
      fullPath: '/resources/policy-briefs'
      preLoaderRoute: typeof ResourcesPolicyBriefsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/gallery': {
      id: '/resources/gallery'
      path: '/gallery'
      fullPath: '/resources/gallery'
      preLoaderRoute: typeof ResourcesGalleryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/blogs': {
      id: '/resources/blogs'
      path: '/blogs'
      fullPath: '/resources/blogs'
      preLoaderRoute: typeof ResourcesBlogsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/reports/project-reports': {
      id: '/reports/project-reports'
      path: '/project-reports'
      fullPath: '/reports/project-reports'
      preLoaderRoute: typeof ReportsProjectReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/financial-reports': {
      id: '/reports/financial-reports'
      path: '/financial-reports'
      fullPath: '/reports/financial-reports'
      preLoaderRoute: typeof ReportsFinancialReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/annual-reports': {
      id: '/reports/annual-reports'
      path: '/annual-reports'
      fullPath: '/reports/annual-reports'
      preLoaderRoute: typeof ReportsAnnualReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/programs/upcoming-programs': {
      id: '/programs/upcoming-programs'
      path: '/upcoming-programs'
      fullPath: '/programs/upcoming-programs'
      preLoaderRoute: typeof ProgramsUpcomingProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/special-programs': {
      id: '/programs/special-programs'
      path: '/special-programs'
      fullPath: '/programs/special-programs'
      preLoaderRoute: typeof ProgramsSpecialProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/our-key-programs': {
      id: '/programs/our-key-programs'
      path: '/our-key-programs'
      fullPath: '/programs/our-key-programs'
      preLoaderRoute: typeof ProgramsOurKeyProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/community-dialogue-programs': {
      id: '/programs/community-dialogue-programs'
      path: '/community-dialogue-programs'
      fullPath: '/programs/community-dialogue-programs'
      preLoaderRoute: typeof ProgramsCommunityDialogueProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/resources/blogs/$slug': {
      id: '/resources/blogs/$slug'
      path: '/$slug'
      fullPath: '/resources/blogs/$slug'
      preLoaderRoute: typeof ResourcesBlogsSlugRouteImport
      parentRoute: typeof ResourcesBlogsRoute
    }
    '/programs/upcoming-programs/$slug': {
      id: '/programs/upcoming-programs/$slug'
      path: '/$slug'
      fullPath: '/programs/upcoming-programs/$slug'
      preLoaderRoute: typeof ProgramsUpcomingProgramsSlugRouteImport
      parentRoute: typeof ProgramsUpcomingProgramsRoute
    }
  }
}

interface ProgramsUpcomingProgramsRouteChildren {
  ProgramsUpcomingProgramsSlugRoute: typeof ProgramsUpcomingProgramsSlugRoute
}

const ProgramsUpcomingProgramsRouteChildren: ProgramsUpcomingProgramsRouteChildren =
  {
    ProgramsUpcomingProgramsSlugRoute: ProgramsUpcomingProgramsSlugRoute,
  }

const ProgramsUpcomingProgramsRouteWithChildren =
  ProgramsUpcomingProgramsRoute._addFileChildren(
    ProgramsUpcomingProgramsRouteChildren,
  )

interface ProgramsRouteChildren {
  ProgramsCommunityDialogueProgramsRoute: typeof ProgramsCommunityDialogueProgramsRoute
  ProgramsOurKeyProgramsRoute: typeof ProgramsOurKeyProgramsRoute
  ProgramsSpecialProgramsRoute: typeof ProgramsSpecialProgramsRoute
  ProgramsUpcomingProgramsRoute: typeof ProgramsUpcomingProgramsRouteWithChildren
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsCommunityDialogueProgramsRoute:
    ProgramsCommunityDialogueProgramsRoute,
  ProgramsOurKeyProgramsRoute: ProgramsOurKeyProgramsRoute,
  ProgramsSpecialProgramsRoute: ProgramsSpecialProgramsRoute,
  ProgramsUpcomingProgramsRoute: ProgramsUpcomingProgramsRouteWithChildren,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsAnnualReportsRoute: typeof ReportsAnnualReportsRoute
  ReportsFinancialReportsRoute: typeof ReportsFinancialReportsRoute
  ReportsProjectReportsRoute: typeof ReportsProjectReportsRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAnnualReportsRoute: ReportsAnnualReportsRoute,
  ReportsFinancialReportsRoute: ReportsFinancialReportsRoute,
  ReportsProjectReportsRoute: ReportsProjectReportsRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ResourcesBlogsRouteChildren {
  ResourcesBlogsSlugRoute: typeof ResourcesBlogsSlugRoute
}

const ResourcesBlogsRouteChildren: ResourcesBlogsRouteChildren = {
  ResourcesBlogsSlugRoute: ResourcesBlogsSlugRoute,
}

const ResourcesBlogsRouteWithChildren = ResourcesBlogsRoute._addFileChildren(
  ResourcesBlogsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesBlogsRoute: typeof ResourcesBlogsRouteWithChildren
  ResourcesGalleryRoute: typeof ResourcesGalleryRoute
  ResourcesPolicyBriefsRoute: typeof ResourcesPolicyBriefsRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesBlogsRoute: ResourcesBlogsRouteWithChildren,
  ResourcesGalleryRoute: ResourcesGalleryRoute,
  ResourcesPolicyBriefsRoute: ResourcesPolicyBriefsRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LeadershipRoute: LeadershipRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
