/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ResourcesToolkitsGuidesRouteImport } from './routes/resources.toolkits-guides'
import { Route as ResourcesPressStatementsRouteImport } from './routes/resources.press-statements'
import { Route as ResourcesPolicyBriefsRouteImport } from './routes/resources.policy-briefs'
import { Route as ResourcesGalleryRouteImport } from './routes/resources.gallery'
import { Route as ResourcesBlogsRouteImport } from './routes/resources.blogs'
import { Route as ReportsProjectReportsRouteImport } from './routes/reports.project-reports'
import { Route as ReportsFinancialReportsRouteImport } from './routes/reports.financial-reports'
import { Route as ReportsAnnualReportsRouteImport } from './routes/reports.annual-reports'
import { Route as ProgramsUpcomingProgramsRouteImport } from './routes/programs.upcoming-programs'
import { Route as ProgramsSpecialProgramsRouteImport } from './routes/programs.special-programs'
import { Route as ProgramsOurKeyProgramsRouteImport } from './routes/programs.our-key-programs'
import { Route as ProgramsCommunityDialogueProgramsRouteImport } from './routes/programs.community-dialogue-programs'
import { Route as DashboardToolkitsGuidesRouteImport } from './routes/dashboard.toolkits-guides'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard.submissions'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard.programs'
import { Route as DashboardPressStatementsRouteImport } from './routes/dashboard.press-statements'
import { Route as DashboardPolicyBriefsRouteImport } from './routes/dashboard.policy-briefs'
import { Route as DashboardMessagingRouteImport } from './routes/dashboard.messaging'
import { Route as DashboardLeadershipRouteImport } from './routes/dashboard.leadership'
import { Route as DashboardHeroSlidesRouteImport } from './routes/dashboard.hero-slides'
import { Route as DashboardGetInvolvedRouteImport } from './routes/dashboard.get-involved'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardDonationsRouteImport } from './routes/dashboard.donations'
import { Route as DashboardBlogsRouteImport } from './routes/dashboard.blogs'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api.paystack-webhook'
import { Route as ResourcesBlogsSlugRouteImport } from './routes/resources.blogs.$slug'
import { Route as ProgramsUpcomingProgramsSlugRouteImport } from './routes/programs.upcoming-programs.$slug'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ResourcesToolkitsGuidesRoute = ResourcesToolkitsGuidesRouteImport.update({
  id: '/toolkits-guides',
  path: '/toolkits-guides',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesPressStatementsRoute =
  ResourcesPressStatementsRouteImport.update({
    id: '/press-statements',
    path: '/press-statements',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesPolicyBriefsRoute = ResourcesPolicyBriefsRouteImport.update({
  id: '/policy-briefs',
  path: '/policy-briefs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesGalleryRoute = ResourcesGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesBlogsRoute = ResourcesBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ReportsProjectReportsRoute = ReportsProjectReportsRouteImport.update({
  id: '/project-reports',
  path: '/project-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsFinancialReportsRoute = ReportsFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAnnualReportsRoute = ReportsAnnualReportsRouteImport.update({
  id: '/annual-reports',
  path: '/annual-reports',
  getParentRoute: () => ReportsRoute,
} as any)
const ProgramsUpcomingProgramsRoute =
  ProgramsUpcomingProgramsRouteImport.update({
    id: '/upcoming-programs',
    path: '/upcoming-programs',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsSpecialProgramsRoute = ProgramsSpecialProgramsRouteImport.update({
  id: '/special-programs',
  path: '/special-programs',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsOurKeyProgramsRoute = ProgramsOurKeyProgramsRouteImport.update({
  id: '/our-key-programs',
  path: '/our-key-programs',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsCommunityDialogueProgramsRoute =
  ProgramsCommunityDialogueProgramsRouteImport.update({
    id: '/community-dialogue-programs',
    path: '/community-dialogue-programs',
    getParentRoute: () => ProgramsRoute,
  } as any)
const DashboardToolkitsGuidesRoute = DashboardToolkitsGuidesRouteImport.update({
  id: '/toolkits-guides',
  path: '/toolkits-guides',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPressStatementsRoute =
  DashboardPressStatementsRouteImport.update({
    id: '/press-statements',
    path: '/press-statements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPolicyBriefsRoute = DashboardPolicyBriefsRouteImport.update({
  id: '/policy-briefs',
  path: '/policy-briefs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagingRoute = DashboardMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadershipRoute = DashboardLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHeroSlidesRoute = DashboardHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGetInvolvedRoute = DashboardGetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonationsRoute = DashboardDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsRoute = DashboardBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack-webhook',
  path: '/api/paystack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogsSlugRoute = ResourcesBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesBlogsRoute,
} as any)
const ProgramsUpcomingProgramsSlugRoute =
  ProgramsUpcomingProgramsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ProgramsUpcomingProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/get-involved': typeof DashboardGetInvolvedRoute
  '/dashboard/hero-slides': typeof DashboardHeroSlidesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messaging': typeof DashboardMessagingRoute
  '/dashboard/policy-briefs': typeof DashboardPolicyBriefsRoute
  '/dashboard/press-statements': typeof DashboardPressStatementsRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/toolkits-guides': typeof DashboardToolkitsGuidesRoute
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/resources/press-statements': typeof ResourcesPressStatementsRoute
  '/resources/toolkits-guides': typeof ResourcesToolkitsGuidesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/get-involved': typeof DashboardGetInvolvedRoute
  '/dashboard/hero-slides': typeof DashboardHeroSlidesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messaging': typeof DashboardMessagingRoute
  '/dashboard/policy-briefs': typeof DashboardPolicyBriefsRoute
  '/dashboard/press-statements': typeof DashboardPressStatementsRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/toolkits-guides': typeof DashboardToolkitsGuidesRoute
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/resources/press-statements': typeof ResourcesPressStatementsRoute
  '/resources/toolkits-guides': typeof ResourcesToolkitsGuidesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/opportunities': typeof OpportunitiesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/get-involved': typeof DashboardGetInvolvedRoute
  '/dashboard/hero-slides': typeof DashboardHeroSlidesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messaging': typeof DashboardMessagingRoute
  '/dashboard/policy-briefs': typeof DashboardPolicyBriefsRoute
  '/dashboard/press-statements': typeof DashboardPressStatementsRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/toolkits-guides': typeof DashboardToolkitsGuidesRoute
  '/programs/community-dialogue-programs': typeof ProgramsCommunityDialogueProgramsRoute
  '/programs/our-key-programs': typeof ProgramsOurKeyProgramsRoute
  '/programs/special-programs': typeof ProgramsSpecialProgramsRoute
  '/programs/upcoming-programs': typeof ProgramsUpcomingProgramsRouteWithChildren
  '/reports/annual-reports': typeof ReportsAnnualReportsRoute
  '/reports/financial-reports': typeof ReportsFinancialReportsRoute
  '/reports/project-reports': typeof ReportsProjectReportsRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/gallery': typeof ResourcesGalleryRoute
  '/resources/policy-briefs': typeof ResourcesPolicyBriefsRoute
  '/resources/press-statements': typeof ResourcesPressStatementsRoute
  '/resources/toolkits-guides': typeof ResourcesToolkitsGuidesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/programs/upcoming-programs/$slug': typeof ProgramsUpcomingProgramsSlugRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/api/paystack-webhook'
    | '/dashboard/blogs'
    | '/dashboard/donations'
    | '/dashboard/gallery'
    | '/dashboard/get-involved'
    | '/dashboard/hero-slides'
    | '/dashboard/leadership'
    | '/dashboard/messaging'
    | '/dashboard/policy-briefs'
    | '/dashboard/press-statements'
    | '/dashboard/programs'
    | '/dashboard/reports'
    | '/dashboard/submissions'
    | '/dashboard/toolkits-guides'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/resources/press-statements'
    | '/resources/toolkits-guides'
    | '/dashboard/'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/api/paystack-webhook'
    | '/dashboard/blogs'
    | '/dashboard/donations'
    | '/dashboard/gallery'
    | '/dashboard/get-involved'
    | '/dashboard/hero-slides'
    | '/dashboard/leadership'
    | '/dashboard/messaging'
    | '/dashboard/policy-briefs'
    | '/dashboard/press-statements'
    | '/dashboard/programs'
    | '/dashboard/reports'
    | '/dashboard/submissions'
    | '/dashboard/toolkits-guides'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/resources/press-statements'
    | '/resources/toolkits-guides'
    | '/dashboard'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/get-involved'
    | '/leadership'
    | '/opportunities'
    | '/programs'
    | '/reports'
    | '/resources'
    | '/api/paystack-webhook'
    | '/dashboard/blogs'
    | '/dashboard/donations'
    | '/dashboard/gallery'
    | '/dashboard/get-involved'
    | '/dashboard/hero-slides'
    | '/dashboard/leadership'
    | '/dashboard/messaging'
    | '/dashboard/policy-briefs'
    | '/dashboard/press-statements'
    | '/dashboard/programs'
    | '/dashboard/reports'
    | '/dashboard/submissions'
    | '/dashboard/toolkits-guides'
    | '/programs/community-dialogue-programs'
    | '/programs/our-key-programs'
    | '/programs/special-programs'
    | '/programs/upcoming-programs'
    | '/reports/annual-reports'
    | '/reports/financial-reports'
    | '/reports/project-reports'
    | '/resources/blogs'
    | '/resources/gallery'
    | '/resources/policy-briefs'
    | '/resources/press-statements'
    | '/resources/toolkits-guides'
    | '/dashboard/'
    | '/programs/upcoming-programs/$slug'
    | '/resources/blogs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LeadershipRoute: typeof LeadershipRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/resources/toolkits-guides': {
      id: '/resources/toolkits-guides'
      path: '/toolkits-guides'
      fullPath: '/resources/toolkits-guides'
      preLoaderRoute: typeof ResourcesToolkitsGuidesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/press-statements': {
      id: '/resources/press-statements'
      path: '/press-statements'
      fullPath: '/resources/press-statements'
      preLoaderRoute: typeof ResourcesPressStatementsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/policy-briefs': {
      id: '/resources/policy-briefs'
      path: '/policy-briefs'
      fullPath: '/resources/policy-briefs'
      preLoaderRoute: typeof ResourcesPolicyBriefsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/gallery': {
      id: '/resources/gallery'
      path: '/gallery'
      fullPath: '/resources/gallery'
      preLoaderRoute: typeof ResourcesGalleryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/blogs': {
      id: '/resources/blogs'
      path: '/blogs'
      fullPath: '/resources/blogs'
      preLoaderRoute: typeof ResourcesBlogsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/reports/project-reports': {
      id: '/reports/project-reports'
      path: '/project-reports'
      fullPath: '/reports/project-reports'
      preLoaderRoute: typeof ReportsProjectReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/financial-reports': {
      id: '/reports/financial-reports'
      path: '/financial-reports'
      fullPath: '/reports/financial-reports'
      preLoaderRoute: typeof ReportsFinancialReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/annual-reports': {
      id: '/reports/annual-reports'
      path: '/annual-reports'
      fullPath: '/reports/annual-reports'
      preLoaderRoute: typeof ReportsAnnualReportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/programs/upcoming-programs': {
      id: '/programs/upcoming-programs'
      path: '/upcoming-programs'
      fullPath: '/programs/upcoming-programs'
      preLoaderRoute: typeof ProgramsUpcomingProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/special-programs': {
      id: '/programs/special-programs'
      path: '/special-programs'
      fullPath: '/programs/special-programs'
      preLoaderRoute: typeof ProgramsSpecialProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/our-key-programs': {
      id: '/programs/our-key-programs'
      path: '/our-key-programs'
      fullPath: '/programs/our-key-programs'
      preLoaderRoute: typeof ProgramsOurKeyProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/community-dialogue-programs': {
      id: '/programs/community-dialogue-programs'
      path: '/community-dialogue-programs'
      fullPath: '/programs/community-dialogue-programs'
      preLoaderRoute: typeof ProgramsCommunityDialogueProgramsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/dashboard/toolkits-guides': {
      id: '/dashboard/toolkits-guides'
      path: '/toolkits-guides'
      fullPath: '/dashboard/toolkits-guides'
      preLoaderRoute: typeof DashboardToolkitsGuidesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/press-statements': {
      id: '/dashboard/press-statements'
      path: '/press-statements'
      fullPath: '/dashboard/press-statements'
      preLoaderRoute: typeof DashboardPressStatementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policy-briefs': {
      id: '/dashboard/policy-briefs'
      path: '/policy-briefs'
      fullPath: '/dashboard/policy-briefs'
      preLoaderRoute: typeof DashboardPolicyBriefsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messaging': {
      id: '/dashboard/messaging'
      path: '/messaging'
      fullPath: '/dashboard/messaging'
      preLoaderRoute: typeof DashboardMessagingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leadership': {
      id: '/dashboard/leadership'
      path: '/leadership'
      fullPath: '/dashboard/leadership'
      preLoaderRoute: typeof DashboardLeadershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hero-slides': {
      id: '/dashboard/hero-slides'
      path: '/hero-slides'
      fullPath: '/dashboard/hero-slides'
      preLoaderRoute: typeof DashboardHeroSlidesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/get-involved': {
      id: '/dashboard/get-involved'
      path: '/get-involved'
      fullPath: '/dashboard/get-involved'
      preLoaderRoute: typeof DashboardGetInvolvedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donations': {
      id: '/dashboard/donations'
      path: '/donations'
      fullPath: '/dashboard/donations'
      preLoaderRoute: typeof DashboardDonationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs': {
      id: '/dashboard/blogs'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/paystack-webhook': {
      id: '/api/paystack-webhook'
      path: '/api/paystack-webhook'
      fullPath: '/api/paystack-webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blogs/$slug': {
      id: '/resources/blogs/$slug'
      path: '/$slug'
      fullPath: '/resources/blogs/$slug'
      preLoaderRoute: typeof ResourcesBlogsSlugRouteImport
      parentRoute: typeof ResourcesBlogsRoute
    }
    '/programs/upcoming-programs/$slug': {
      id: '/programs/upcoming-programs/$slug'
      path: '/$slug'
      fullPath: '/programs/upcoming-programs/$slug'
      preLoaderRoute: typeof ProgramsUpcomingProgramsSlugRouteImport
      parentRoute: typeof ProgramsUpcomingProgramsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBlogsRoute: typeof DashboardBlogsRoute
  DashboardDonationsRoute: typeof DashboardDonationsRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardGetInvolvedRoute: typeof DashboardGetInvolvedRoute
  DashboardHeroSlidesRoute: typeof DashboardHeroSlidesRoute
  DashboardLeadershipRoute: typeof DashboardLeadershipRoute
  DashboardMessagingRoute: typeof DashboardMessagingRoute
  DashboardPolicyBriefsRoute: typeof DashboardPolicyBriefsRoute
  DashboardPressStatementsRoute: typeof DashboardPressStatementsRoute
  DashboardProgramsRoute: typeof DashboardProgramsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardToolkitsGuidesRoute: typeof DashboardToolkitsGuidesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBlogsRoute: DashboardBlogsRoute,
  DashboardDonationsRoute: DashboardDonationsRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardGetInvolvedRoute: DashboardGetInvolvedRoute,
  DashboardHeroSlidesRoute: DashboardHeroSlidesRoute,
  DashboardLeadershipRoute: DashboardLeadershipRoute,
  DashboardMessagingRoute: DashboardMessagingRoute,
  DashboardPolicyBriefsRoute: DashboardPolicyBriefsRoute,
  DashboardPressStatementsRoute: DashboardPressStatementsRoute,
  DashboardProgramsRoute: DashboardProgramsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardToolkitsGuidesRoute: DashboardToolkitsGuidesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProgramsUpcomingProgramsRouteChildren {
  ProgramsUpcomingProgramsSlugRoute: typeof ProgramsUpcomingProgramsSlugRoute
}

const ProgramsUpcomingProgramsRouteChildren: ProgramsUpcomingProgramsRouteChildren =
  {
    ProgramsUpcomingProgramsSlugRoute: ProgramsUpcomingProgramsSlugRoute,
  }

const ProgramsUpcomingProgramsRouteWithChildren =
  ProgramsUpcomingProgramsRoute._addFileChildren(
    ProgramsUpcomingProgramsRouteChildren,
  )

interface ProgramsRouteChildren {
  ProgramsCommunityDialogueProgramsRoute: typeof ProgramsCommunityDialogueProgramsRoute
  ProgramsOurKeyProgramsRoute: typeof ProgramsOurKeyProgramsRoute
  ProgramsSpecialProgramsRoute: typeof ProgramsSpecialProgramsRoute
  ProgramsUpcomingProgramsRoute: typeof ProgramsUpcomingProgramsRouteWithChildren
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsCommunityDialogueProgramsRoute:
    ProgramsCommunityDialogueProgramsRoute,
  ProgramsOurKeyProgramsRoute: ProgramsOurKeyProgramsRoute,
  ProgramsSpecialProgramsRoute: ProgramsSpecialProgramsRoute,
  ProgramsUpcomingProgramsRoute: ProgramsUpcomingProgramsRouteWithChildren,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsAnnualReportsRoute: typeof ReportsAnnualReportsRoute
  ReportsFinancialReportsRoute: typeof ReportsFinancialReportsRoute
  ReportsProjectReportsRoute: typeof ReportsProjectReportsRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAnnualReportsRoute: ReportsAnnualReportsRoute,
  ReportsFinancialReportsRoute: ReportsFinancialReportsRoute,
  ReportsProjectReportsRoute: ReportsProjectReportsRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ResourcesBlogsRouteChildren {
  ResourcesBlogsSlugRoute: typeof ResourcesBlogsSlugRoute
}

const ResourcesBlogsRouteChildren: ResourcesBlogsRouteChildren = {
  ResourcesBlogsSlugRoute: ResourcesBlogsSlugRoute,
}

const ResourcesBlogsRouteWithChildren = ResourcesBlogsRoute._addFileChildren(
  ResourcesBlogsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesBlogsRoute: typeof ResourcesBlogsRouteWithChildren
  ResourcesGalleryRoute: typeof ResourcesGalleryRoute
  ResourcesPolicyBriefsRoute: typeof ResourcesPolicyBriefsRoute
  ResourcesPressStatementsRoute: typeof ResourcesPressStatementsRoute
  ResourcesToolkitsGuidesRoute: typeof ResourcesToolkitsGuidesRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesBlogsRoute: ResourcesBlogsRouteWithChildren,
  ResourcesGalleryRoute: ResourcesGalleryRoute,
  ResourcesPolicyBriefsRoute: ResourcesPolicyBriefsRoute,
  ResourcesPressStatementsRoute: ResourcesPressStatementsRoute,
  ResourcesToolkitsGuidesRoute: ResourcesToolkitsGuidesRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LeadershipRoute: LeadershipRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
